package:
  name: sprit
  version: 1.2-dev

source:
  git_url: https://github.com/RJbalikian/SPRIT-HVSR
  git_tag: v1.2-dev

build:
  number: 0
  script:
    - python -m pip install . -vv
    - python -m pytest --pyargs sprit

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - obspy
    - scipy
    - matplotlib
    - pandas
    - numpy
    - pyqt5-sip
    - pyproj

about:
  home: https://github.com/RJbalikian/SPRIT-HVSR
  api: https://rjbalikian.github.io/SPRIT-HVSR/main.html
  license: MIT
  summary: A package for processing and analyzing HVSR (Horizontal to Vertical Spectral Ratio) seismic data


#build:
#  number: 0
#  entry_points:
#    - my_script = my_package.module:main_function

#requirements:
#  host:
#    - python
#    - setuptools
#  run:
#    - python
