FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Avoid tzdata prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install APT packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    wget \
    build-essential \
``
